services:
  - type: web
    name: real-stay-api
    env: node
    repo: https://github.com/chijiooke/real-stay
    branch: main
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false  # Set this in the dashboard for security
      - key: MAILER_HOST
        value: smtp-relay.brevo.com
      - key: MAILER_PORT
        value: 587
      - key: BREVO_EMAIL
        value: 88b6ca003@smtp-brevo.com
      - key: BREVO_API_KEY
        sync: false  # Set this in the dashboard for security


